import type { Dialect, Song } from "../engine/types.js";
import { chordDisplayName, scaleOf } from "../engine/harmony.js";
import { generateLyrics } from "../engine/lyrics.js";

/**
 * Suno 等の外部サービス向けテキスト出力 (§4.5)。
 * スタイルプロンプト+セクション別の仮歌詞+コード進行をまとめる。
 */

const SECTION_LABELS: Record<string, string> = {
  intro: "Intro", verse: "Verse", chorus: "Chorus", bridge: "Bridge", outro: "Outro",
};

const FLAT_KEYS = new Set(["F", "Bb", "Eb", "Ab", "Db", "Gb"]);

export function buildSunoText(song: Song, dialect: Dialect | undefined): string {
  const lyrics = generateLyrics(song);
  const useFlats = FLAT_KEYS.has(song.keyName);
  const scalePcs = scaleOf(song.key);
  const lines: string[] = [];

  lines.push("=== Style Prompt (Suno の Style of Music 欄へ) ===");
  lines.push(dialect?.stylePrompt ?? "pop song");
  lines.push(`Key: ${song.keyName} ${song.key.mode}, Tempo: ${song.bpm} BPM`);
  lines.push("");

  lines.push("=== Lyrics (仮歌詞: 差し替え推奨) ===");
  const counts: Record<string, number> = {};
  song.sections.forEach((section, i) => {
    const label = SECTION_LABELS[section.plan.type] ?? section.plan.type;
    counts[label] = (counts[label] ?? 0) + 1;
    lines.push(`[${label} ${counts[label]}]`);
    for (const line of lyrics[i]?.lines ?? []) {
      lines.push(line);
    }
    lines.push("");
  });

  lines.push("=== Chord Progression (参考) ===");
  const counts2: Record<string, number> = {};
  song.sections.forEach((section) => {
    const label = SECTION_LABELS[section.plan.type] ?? section.plan.type;
    counts2[label] = (counts2[label] ?? 0) + 1;
    const chordNames = section.chords
      .map((c) => chordDisplayName(c, useFlats, scalePcs))
      .join(" | ");
    lines.push(`${label} ${counts2[label]}: ${chordNames}`);
  });
  lines.push("");
  lines.push(`generated by melodialect (dialect: ${song.dialectId}, seed: ${song.seed})`);

  return lines.join("\n");
}

export function downloadSunoText(song: Song, dialect: Dialect | undefined): void {
  const text = buildSunoText(song, dialect);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `melodialect-${song.dialectId}-seed${song.seed}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
